export const columns = (label, captions, { communitiesData, allTime }) => [
  {
    id: 'allTime',
    caption: captions[0],
    defaultWidth: '100px',
    type: 'date',
    label: label[1],
    columnData: allTime,
    filterWidth: 130,
    align: 'center',
    noData: true,
    disablePadding: true,
    show: true,
    sortable: true,
    filter: true,
    defaultFilter: true,
    custom: false,
  },
  {
    id: 'communities',
    caption: captions[1],
    type: 'levels',
    label: label[0],
    filterWidth: 200,
    align: 'left',
    noData: false,
    columnData: communitiesData,
    disablePadding: true,
    show: true,
    sortable: false,
    filter: true,
    defaultFilter: true,
    custom: false,
  },
];
